# UI constants, local to the ui/ package

# menu constants
MENU_TITLE_FONT_SIZE = 64
MENU_OPTION_FONT_SIZE = 40
MENU_OPTION_SPACING = 60

# controls screen constants
CONTROLS_TEXT_FONT_SIZE = 32
CONTROLS_LINE_SPACING = 44

# menu leaderboard panel constants
LEADERBOARD_PANEL_MARGIN = 40
LEADERBOARD_HEADER_FONT_SIZE = 36
LEADERBOARD_ENTRY_FONT_SIZE = 28
LEADERBOARD_ENTRY_SPACING = 32
