# gameplay constants, local to the game/ package

# shared rendering
LINE_WIDTH = 2

# player constants
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# shot constants
SHOT_RADIUS = 5

# asteroid constants
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SPLIT_SPEED_INCREASE = 1.2

# score constants
SCORE_PER_SECOND = 10
SCORE_PER_ASTEROID_HIT = 10
SCORE_FONT_SIZE = 36
SCORE_MARGIN = 10
