# RL env constants, local to the rl/ package
FIXED_DT = 1 / 60

N_NEAREST_ASTEROIDS = 10
PLAYER_OBSERVATION_SIZE = 5
ASTEROID_OBSERVATION_SIZE = 6
OBSERVATION_SIZE = PLAYER_OBSERVATION_SIZE + N_NEAREST_ASTEROIDS * ASTEROID_OBSERVATION_SIZE

REL_VELOCITY_SCALE = 1 / 100

DEATH_PENALTY = -100

BOUNDARY_PENALTY = 1
